RestaurantReviewConsole/RestaurantReviewWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RestaurantReviewWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

RestaurantReviewConsole/RestaurantReviewWeb/Controllers/RestaurantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RestaurantReviewLibrary.Models;
using RestaurantReviewLibrary;
using RestaurantReviewData;

namespace RestaurantReviewWeb.Controllers
{
    public class RestaurantsController : Controller
    {
        static RestaurantReviewManager webManager = new RestaurantReviewManager();
        private static List<LibRestaurant> restaurants = webManager.PrintRestaurants();

        // GET: Restaurants
        public ActionResult Index()
        {
            return View(webManager.PrintRestaurants());
        }

        public ActionResult SortedIndex(List<LibRestaurant> sortedRestaurants)
        {
            return View(sortedRestaurants);
        }

        public ActionResult Details(int ID)
        {
            return View(webManager.PrintRestaurants().First(x => x.ID == ID));
        }

        public ActionResult CreateRestaurant()
        {
            return View();
        }

        public ActionResult DeleteRestaurant(int id)
        {
            return View(webManager.PrintRestaurants().First(x => x.ID == id));
        }

        public ActionResult Edit(int ID)
        {
            return View(restaurants.First(x => x.ID == ID));
        }

        public ActionResult SortByRatingDescending()
        {
            List<LibRestaurant> sortedList = webManager.SortByRating("descending", restaurants);
            return View("Index", sortedList);
        }

        public ActionResult SortByRatingAscending()
        {
            List<LibRestaurant> sortedList = webManager.SortByRating("ascending", restaurants);
            return View("Index", sortedList);
        }

        public ActionResult SortByNameAscending()
        {
            List<LibRestaurant> sortedList = webManager.SortByName("ascending", restaurants);
            return View("Index", sortedList);
        }

        public ActionResult SortByNameDescending()
        {
            List<LibRestaurant> sortedList = webManager.SortByName("descending", restaurants);
            return View("Index", sortedList);
        }

        public ActionResult DisplayTop3()
        {
            List<LibRestaurant> top3List = new List<LibRestaurant>();

            for(int i = 0; i < 3; i++)
            {
                top3List.Add(webManager.SortByRating("descending", restaurants).ElementAt(i));
            }

            return View("Index", top3List);
        }

        public ActionResult Search(string name)
        {
            return View(webManager.SearchRestByName(name));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateRestaurant(/*[Bind(Include = "ID, Name, Address, City, Country, ZIP")]*/LibRestaurant restaurant)
        {
            try
            {
                webManager.AddRestaurantToDB(restaurant);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
    }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(/*[Bind(Include = "ID, Name, Address, City, Country, ZIP")]*/int id, LibRestaurant newRestaurant)
        {
            try
            {
                var oldRestaurant = restaurants.First(x => x.ID == id);

                webManager.UpdateRestaurantInDB(newRestaurant);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteRestaurant(/*[Bind(Include = "ID, Name, Address, City, Country, ZIP")]*/LibRestaurant delete)
        {
            try
            {
                webManager.DeleteRestaurantFromDB(delete.ID);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

RestaurantReviewConsole/RestaurantReviewWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>About Global Eats.</h2>
<h3>Never established, still providing quality</h3>

<p>We&acute;ve worked diligently to collect information on restaurants around the world. We&acute;re so good, we even found twenty restaurants that don't exist!!! Through hard work, we&acute;re delivering these restaurants to you. Most of these restaurants even have reviews! If you can read lorem ipsum, you can read our reviews! Have fun!</p>

RestaurantReviewConsole/RestaurantReviewWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>Contact Global Eats!</h2>
<h3>Questions, comments, complaints? Sam wants to hear them all!</h3>

<address>
    1 Solar Way<br />
    Center of the Sun, Get a Rocket<br />
    <abbr title="Phone">P:</abbr>
    111.555.1234
</address>

<address>
    <strong>Support:</strong>   Sam@GlobalEats.Com<br />
</address>

RestaurantReviewConsole/RestaurantReviewWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Global Eats</h1>
    <p class="lead">Welcome to Global Eats! We collected information on twenty restaurants that don't exist!</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>View Our Restaurants</h2>
        <p>
            Have a look at all twenty restaurants we&acute;ve collected data on!
        </p>
        <p>@Html.ActionLink("Go Now!", "Index", "Restaurants")</p>
    </div>
    <div class="col-md-4">
        <h2>Learn More About Us!</h2>
        <p>This page will tell you all about our company and our mission. It's really quite interesting, we suggest taking a look.</p>
        <p>@Html.ActionLink("Go Now!", "About", "Home")</p>
    </div>
    <div class="col-md-4">
        <h2>Contact Us!</h2>
        <p>Got a problem? Talk to Sam.</p>
        <p>@Html.ActionLink("Go Now!", "Contact", "Home")</p>
    </div>
</div>